### ISSUE TITLE
Cannot find module 'lodash'

### ISSUE THREAD

**Issue by vinaybedre** [miguelmota/C4.5#1]
Hi,

When I executed the sample given at https://www.npmjs.com/package/c4.5 I get following error message. Can you please fix this?

Error: Cannot find module 'lodash'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:278:25)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/Users/i070514/dev/node/c4algo/node_modules/c4.5/C45.js:1:71)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)

**Comment by miguelmota** [comment]
@vinaybedre this module doesn't use lodash at all. Try `npm install lodash --save` on your end.
